### ISSUE TITLE
Failed to add user

### ISSUE THREAD

**Issue by JojoWu19** [DMTF/Redfish-Usecase-Checkers#35]
When we run the account_management.py, we get the result with failed to add user (Base.1.6.MalformedJSON).
After checking account_management.py as below:
```
        # Create a new user
            ...
            redfish_utilities.modify_user( redfish_obj, test_username, new_enabled = True )
            ...
```
Here should use `new_enabled = true` , right?

**Comment by mraineri** [comment]
No, this is the Python literal `True`; when it's serialized into JSON, it will get converted to `true`.

**Comment by JojoWu19** [comment]
Yes, I also think this is not the root cause.
I will create the other issue to discuss.
thank you.
