### ISSUE TITLE
accounts  deleted from dell but output says not deleted.

### ISSUE THREAD

**Issue by cb371j** [DMTF/Redfish-Usecase-Checkers#44]
Hi, I tested the new files.  The accounts are delete but the results.json say not deleted.

[account_management_resutls.docx](https://github.com/DMTF/Redfish-Usecase-Checkers/files/4636842/account_management_resutls.docx)

**Comment by cb371j** [comment]
root@testingvm:/home/cb371j/213# pip show redfish_utilities
Name: redfish-utilities
Version: 1.0.6
Summary: Redfish Utilities
Home-page: https://github.com/DMTF/Redfish-Tacklebox
Author: DMTF, https://www.dmtf.org/standards/feedback
Author-email: None
License: BSD 3-clause "New" or "Revised License"
Location: /usr/local/lib/python2.7/dist-packages
Requires: redfish

**Comment by mraineri** [comment]
@cb371j I created a branch called "account-debug"; could you please run the modifications in this branch and provide the console output from the test execution? It'll print the trace of the exception that leads to the error being seen in your report.

https://github.com/DMTF/Redfish-Usecase-Checkers/tree/account-debug

**Comment by cb371j** [comment]
I had upgraded redfish_utilities Friday.  Today I upgraded it again and redfishtool and redfish.    No errors and accounts deleted successfully.  Thank you so much.

{
    "ToolName": "Account Management",
    "Timestamp": {
        "DateTime": "2020-05-18T14:50:19Z"
    },
    "ServiceRoot": {
        "@odata.context": "/redfish/v1/$metadata#ServiceRoot.ServiceRoot",
        "@odata.id": "/redfish/v1",
        "@odata.type": "#ServiceRoot.v1_3_0.ServiceRoot",
        "AccountService": {
            "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/AccountService"
        },
        "Chassis": {
            "@odata.id": "/redfish/v1/Chassis"
        },
        "Description": "Root Service",
        "EventService": {
            "@odata.id": "/redfish/v1/EventService"
        },
        "Fabrics": {
            "@odata.id": "/redfish/v1/Fabrics"
        },
        "Id": "RootService",
        "JsonSchemas": {
            "@odata.id": "/redfish/v1/JSONSchemas"
        },
        "Links": {
            "Sessions": {
                "@odata.id": "/redfish/v1/Sessions"
            }
        },
        "Managers": {
            "@odata.id": "/redfish/v1/Managers"
        },
        "Name": "Root Service",
        "Oem": {
            "Dell": {
                "@odata.context": "/redfish/v1/$metadata#DellServiceRoot.DellServiceRoot",
                "@odata.type": "#DellServiceRoot.v1_0_0.ServiceRootSummary",
                "IsBranded": 0,
                "ManagerMACAddress": "d0:94:66:6b:84:66",
                "ServiceTag": "HPSY0Q2"
            }
        },
        "Product": "Integrated Dell Remote Access Controller",
        "ProtocolFeaturesSupported": {
            "ExpandQuery": {
                "ExpandAll": true,
                "Levels": true,
                "Links": true,
                "MaxLevels": 1,
                "NoLinks": true
            },
            "FilterQuery": true,
            "SelectQuery": true
        },
        "RedfishVersion": "1.4.0",
        "Registries": {
            "@odata.id": "/redfish/v1/Registries"
        },
        "SessionService": {
            "@odata.id": "/redfish/v1/SessionService"
        },
        "Systems": {
            "@odata.id": "/redfish/v1/Systems"
        },
        "Tasks": {
            "@odata.id": "/redfish/v1/TaskService"
        },
        "UpdateService": {
            "@odata.id": "/redfish/v1/UpdateService"
        }
    },
    "TestResults": {
        "User Count": {
            "pass": 1,
            "fail": 0,
            "skip": 0
        },
        "Add User": {
            "pass": 2,
            "fail": 0,
            "skip": 0
        },
        "Enable User": {
            "pass": 1,
            "fail": 0,
            "skip": 0
        },
        "Credential Check": {
            "pass": 2,
            "fail": 0,
            "skip": 0
        },
        "Change Role": {
            "pass": 6,
            "fail": 0,
            "skip": 0
        },
        "Delete User": {
            "pass": 2,
            "fail": 0,
            "skip": 0
        }
    }
}



{
    "ToolName": "Account Management",
    "Timestamp": {
        "DateTime": "2020-05-18T14:49:34Z"
    },
    "ServiceRoot": {
        "@odata.context": "/redfish/v1/$metadata#ServiceRoot.ServiceRoot",
        "@odata.id": "/redfish/v1",
        "@odata.type": "#ServiceRoot.v1_3_0.ServiceRoot",
        "AccountService": {
            "@odata.id": "/redfish/v1/Managers/iDRAC.Embedded.1/AccountService"
        },
        "Chassis": {
            "@odata.id": "/redfish/v1/Chassis"
        },
        "Description": "Root Service",
        "EventService": {
            "@odata.id": "/redfish/v1/EventService"
        },
        "Fabrics": {
            "@odata.id": "/redfish/v1/Fabrics"
        },
        "Id": "RootService",
        "JsonSchemas": {
            "@odata.id": "/redfish/v1/JSONSchemas"
        },
        "Links": {
            "Sessions": {
                "@odata.id": "/redfish/v1/Sessions"
            }
        },
        "Managers": {
            "@odata.id": "/redfish/v1/Managers"
        },
        "Name": "Root Service",
        "Oem": {
            "Dell": {
                "@odata.context": "/redfish/v1/$metadata#DellServiceRoot.DellServiceRoot",
                "@odata.type": "#DellServiceRoot.v1_0_0.ServiceRootSummary",
                "IsBranded": 0,
                "ManagerMACAddress": "d0:94:66:6a:24:8f",
                "ServiceTag": "HPTT0Q2"
            }
        },
        "Product": "Integrated Dell Remote Access Controller",
        "ProtocolFeaturesSupported": {
            "ExpandQuery": {
                "ExpandAll": true,
                "Levels": true,
                "Links": true,
                "MaxLevels": 1,
                "NoLinks": true
            },
            "FilterQuery": true,
            "SelectQuery": true
        },
        "RedfishVersion": "1.4.0",
        "Registries": {
            "@odata.id": "/redfish/v1/Registries"
        },
        "SessionService": {
            "@odata.id": "/redfish/v1/SessionService"
        },
        "Systems": {
            "@odata.id": "/redfish/v1/Systems"
        },
        "Tasks": {
            "@odata.id": "/redfish/v1/TaskService"
        },
        "UpdateService": {
            "@odata.id": "/redfish/v1/UpdateService"
        }
    },
    "TestResults": {
        "User Count": {
            "pass": 1,
            "fail": 0,
            "skip": 0
        },
        "Add User": {
            "pass": 2,
            "fail": 0,
            "skip": 0
        },
        "Enable User": {
            "pass": 1,
            "fail": 0,
            "skip": 0
        },
        "Credential Check": {
            "pass": 2,
            "fail": 0,
            "skip": 0
        },
        "Change Role": {
            "pass": 6,
            "fail": 0,
            "skip": 0
        },
        "Delete User": {
            "pass": 2,
            "fail": 0,
            "skip": 0
        }
    }
}

**Comment by mraineri** [comment]
Glad to hear it! Sounds like you might have been using an older version of redfish_utilities when you first ran the test. Please let us know if this crops up again.
