### ISSUE TITLE
power_control.py is failing on both Dell and Nokia

### ISSUE THREAD

**Issue by cb371j** [DMTF/Redfish-Usecase-Checkers#49]
cloned latest code this morning.  power_control.py is failing on both Dell and Nokia servers.  Results in doc. 
[power_control_results.docx](https://github.com/DMTF/Redfish-Usecase-Checkers/files/4891407/power_control_results.docx)

**Comment by mraineri** [comment]
Unfortunately those are real conformance issues with those implementations. They are breaking the guidance in the spec to allow for operations like that if the system is already in the desired state.

We have the following statement in the "POST (Action)" clause of the Redfish Specification:

> If an action requested by the client will have no effect, such as performing a reset of a `ComputerSystem` where the `ResetType` parameter is set to `On` and the `ComputerSystem` is already `On`, the service should respond with the HTTP `200 OK` status code and return the `NoOperation` message from the Base Message Registry.

Returning a 400 or a 409 is not good behavior for the service. I would recommend reaching out to your customer service contacts for those systems.
