### ISSUE TITLE
Timeout needs to be increased for Power Control

### ISSUE THREAD

**Issue by ldonova1992** [DMTF/Redfish-Usecase-Checkers#59]
There is currently a 10 second timeout after each reset in the Power Control test. I'm finding that on some systems that is not long enough. I'd like to make changes to be able to use an input parameter to the script so that the user can define what's needed and it can default to 10 seconds if nothing is inputted. I'll make a pull request and link it to this issue

**Comment by jautor** [comment]
Thanks for the PR and the enhancement.  Simple addition and yes, I can see why it may be useful.
