### ISSUE TITLE
New Redfish-Usecase-Checkers fails if ServiceRoot/JsonSchemas is not available

### ISSUE THREAD

**Issue by jbobzin-insyde** [DMTF/Redfish-Usecase-Checkers#6]
New Redfish-Usecase-Checkers fails if ServiceRoot/JsonSchemas is not available.
I was testing Account section.
In separate thread mraineri said
JsonSchemas is not required to be implemented; the property "JsonSchemas" in ServiceRoot_v1.xml is not annotated with Redfish.Required. This sounds like a bug in the Usecase Checkers.

https://github.com/DMTF/spmf/issues/2097

**Comment by billdodd** [comment]
Thanks for the report. Agree this is a bug. Will be fixed in next Pull request.
