### ISSUE TITLE
Failure in power_thermal_info when Chassis does not have Power or Thermal info

### ISSUE THREAD

**Issue by ldonova1992** [DMTF/Redfish-Usecase-Checkers#61]
I'm running into a failure on a PowerEdge when running the power_thermal_info test. Through debugging it looks like a Chassis endpoint does not have power/thermal modules (EnvironmentMetrics, PowerSubsystem, ThermalSubsystem, Power or Thermal). It is it valid that it fails here or should the chassis that does not have these modules just be skipped? 

If this is a valid failure, should the logging be more descriptive to catch this error instead of returning a TypeError?

![image](https://user-images.githubusercontent.com/45437442/169828002-64ce30c8-f41f-47e1-8cfb-6ac9098ac103.png)

**Comment by mraineri** [comment]
It's expected there should be at least something in the Chassis resource. The Status property in Chassis is considered a sensor reading for this test. So, having other resources like Power and Thermal are not necessary.

I'm wondering if there is a null property in the resource where not expected. What's the value of the "Name" property in the Chassis resource in question? I can see an improper implementation filling "Name" with null, which would result in that type of exception (assuming none of the subordinate resources like Power and Thermal are implemented).

**Comment by ldonova1992** [comment]
"Name": "PCIe SSD Backplane 0"

I do see null in PartNumber, SerialNumber, Manufacturer and some Dell OEM properties, but thats it

**Comment by mraineri** [comment]
Prior to line 59 in power_thermal_test.py, can you add "print( sensors )" so it shows the raw data as-is? That will help me narrow down what reading is causing the exception.

**Comment by mraineri** [comment]
@ldonova1992 there should be a fix available in the `redfish_utilities` package. Can you try again after updating to version 1.2.4?

`pip3 install -U redfish_utilities`

**Comment by mraineri** [comment]
Closing; updates to Tacklebox should address this. If this issue persists, please reopen.
